apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: prod
  labels:
    name:  nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
        - image:  pblgllgs/pod:blue
          name:  nginx
          ports:
            - containerPort: 80
